name: Deploy Backend to Cloud Run

on:
  push:
    branches:
      - main
    paths:
      - "apps/core/**"
      - ".github/workflows/deploy-backend.yml"

env:
  PROJECT_ID: aura-484013
  REGION: us-central1
  SERVICE_NAME: aura-backend

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Auth via Workload Identity Federation (Keyless)
      - id: "auth"
        uses: "google-github-actions/auth@v2"
        with:
          workload_identity_provider: "projects/430265422877/locations/global/workloadIdentityPools/github-pool/providers/github-provider-secure"
          service_account: "github-deployer@aura-484013.iam.gserviceaccount.com"

      # Deploy to Cloud Run
      - name: "Deploy to Cloud Run"
        uses: "google-github-actions/deploy-cloudrun@v2"
        with:
          source: "apps/core"
          service: "${{ env.SERVICE_NAME }}"
          region: "${{ env.REGION }}"
          project_id: "${{ env.PROJECT_ID }}"
          flags: "--allow-unauthenticated"
